# This pipeline is connected to the GAIA-X4PLC-AAD/self-description-creator Github repository, it recognizes code changes on the master branch and have no library access.
# By executing this pipeline, the build-and-deployment pipeline of the self-description-creator in azure devops is executed.
# This trigger is necessary because the Repository resource triggers only work for Azure Repos Git repositories in the same organization and when the self repository type is Azure Repos Git.
# They do not work for GitHub or Bitbucket repository resources.

trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo Changes on master branch detected
      echo Start build-and-deployment pipeline
    displayName: 'Changes detected'
