version: '3'
services:

  self-description-creator:
    build: ./
    ports:
      - "80:8080"
    environment:
      OPERATING_MODE: "API"
#      CLAIM_FILES_DIR: "/mnt/data"
#      - KEYCLOAK_USER
#      - KEYCLOAK_PASSWORD
#      - KEYCLOAK_CLIENT_SECRET
#    volumes:
#      - ./data/:/mnt/data/

