version: '3'
services:

  self-description-creator:
    build: ./
    ports:
      - "8080:8080"
    environment:
      CREDENTIAL_ISSUER: ""
      CREDENTIAL_ISSUER_PRIVATE_KEY_PEM_PATH: "/mnt/cert/<pem_file_name>"
#      KEYCLOAK_SERVER_URL: ""
#      KEYCLOAK_CLIENT_SECRET: ""
#      FEDERATED_CATALOGUE_USER_NAME: ""
#      FEDERATED_CATALOGUE_USER_PASSWORD: ""
#      FEDERATED_CATALOGUE_URL: ""
#      USE_LEGACY_CATALOGUE_SIGNATURE: True
#      CLAIM_FILES_DIR: "/mnt/data"
#      DID_STORAGE_TYPE: "local"
#      DID_STORAGE_PATH": ""
    volumes:
      - <local_folder_cert_file>/:/mnt/cert/
#      - <local_folder_claims_files>:/mnt/data/

