{{- if .Values.volume.storageClassName -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volume.claimName | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.storageSize }}
  storageClassName: {{ .Values.volume.storageClassName | quote }}
{{- end }}

---

{{- if .Values.didVolume.storageClassName -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.didVolume.claimName | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.didVolume.storageSize }}
  storageClassName: {{ .Values.didVolume.storageClassName | quote }}
{{- end }}
