{{- if or .Values.federatedCatalogue.user.password .Values.keycloak.realm.client_secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-chart.fullname" . }}-secret
data:
  {{- if .Values.federatedCatalogue.user.password }}
  federated_catalogue_user_name: {{ default "" .Values.federatedCatalogue.user.name | b64enc | quote }}
  federated_catalogue_user_password: {{ default "" .Values.federatedCatalogue.user.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.keycloak.realm.client_secret }}
  keycloak_client_secret: {{ toString .Values.keycloak.realm.client_secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.credentialIssuer.privateKeyPem }}
  credential_issuer_private_key_pem: {{ toString .Values.credentialIssuer.privateKeyPem | b64enc | quote }}
  {{- end }}
{{- end }}